config/routes.rb
MagicTv::Application.routes.draw do

  resources :programs do
    get :mail, format: true, default: {format: :text}, on: :collection
    member do
      put "moderate/:status", action: :moderate, as: :moderate
    end
  end

  resource :import, only: [:new, :create]

  resource :user do
    get :help
    get :resend_activation
    get "activate/:key", action: :activate, as: :activate
    get "unsubscribe/:key", action: :unsubscribe, as: :unsubscribe
  end
  match "/auth/:provider/callback" => "users#omniauth"

  match "session/destroy"

  root :to => 'programs#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :programs
    can :access, :users
    cannot [:read, :update, :destory], :users
    can :access, :session
    if user
      case user.role
      when "admin"
        can :access, :all
      when "moderator"
        can :access, :imports
        can :access, :programs
        can :access, :users
      else
        can :create, :programs
        can [:update, :destroy], :programs, user_id: user.id
        can :access, :users
      end
    end
  end
end

app/models/auth.rb
class Auth < ActiveRecord::Base
  serialize :omni_hash, Hash
  belongs_to :user
end

app/models/program.rb
class Program < ActiveRecord::Base
  STATUSES = [:draft, :ok, :ng]
  acts_as_taggable
  belongs_to :user

  validates_presence_of :name, :start_at

  def self.import
    draft_count = Program.where(status: :draft).count
    keywords = YAML.load_file(Rails.root.join("db/keywords.yml"))
    keywords.each do |keyword, query|
      query ||= keyword
      uri = "http://tv.so-net.ne.jp/rss/schedulesBySearch.action?stationPlatformId=0&condition.keyword=#{URI::encode(query)}"
      posts = FeedNormalizer::FeedNormalizer.parse open uri
      posts.entries.each do |post|
        uid = post.url
        e = Program.find_or_initialize_by_uid(uid) do |e|
          parsed = post.content.force_encoding('utf-8').match(/.+ (.+)～(.+) \[(.+)\]/)
          e.assign_attributes(
            name: post.title.force_encoding('utf-8'),
            start_at: post.date_published,
            end_at: nil, #todo
            channel: parsed[3],
            url: post.url,
            status: :draft
          )
          draft_count += 1
        end
        e.tag_list << keyword
        e.save!
        return if draft_count > 200
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :auths
  ROLES = [:contributor, :moderator, :admin]

  validates :email, uniqueness: true, format: {with: /@/}, allow_blank: true
  validates_presence_of :email, on: :create

  before_save do
    if email_changed?
      self.email_active = false
      self.key = SecureRandom.hex(16)
      UserMailer.activate(self).deliver if email.present?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  enable_authorization
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def new
    @programs = Program.includes(:base_tags).where(status: :draft).where("start_at > ?", Time.now).order("start_at ASC")
    @current_tags = []
  end
end

app/controllers/programs_controller.rb
# coding: utf-8

class ProgramsController < ApplicationController
  load_and_authorize_resource
  permits :url, :name, :description, :channel, :tag_list, :start_at, :end_at

  # GET /programs
  def index
    @programs = @programs.includes(:base_tags).where(status: :ok).where("start_at > ?", Time.now).order("start_at ASC")
    @current_tags = params[:tag].to_s.split(',')
    @programs = @programs.tagged_with(@current_tags) if @current_tags.present?
  end

  def mail
    render text: UserMailer.programs(current_user).body.parts[0].body.raw_source
  end

  # GET /programs/1
  def show(id)
  end

  # GET /programs/new
  def new
  end

  # GET /programs/1/edit
  def edit(id)
  end

  # POST /programs
  def create(program)
    @program.status = can?(:moderate, :programs) ? :ok : :draft

    if @program.save
      redirect_to @program, notice: '番組情報が投稿されました。モデレータに承認されると他のユーザーにも表示されます。'
    else
      render action: 'new'
    end
  end

  # PUT /programs/1
  def update(id, program)
    @program = Program.find(id)

    if @program.update_attributes(program)
      respond_to do |format|
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.js { head :ok }
      end
    else
      respond_to do |format|
        format.html { render action: 'edit' }
        format.js { render json: { errors: @program.errors.messages } }
      end
    end
  end

  def moderate(id, status)
    @program.update_attributes(user_id: current_user.id, status: status)
    head :ok
  end

  # DELETE /programs/1
  def destroy(id)
    @program = Program.find(id)
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.js { head :ok }
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました"
  end
end

app/controllers/users_controller.rb
# coding: utf-8

class UsersController < ApplicationController
  permits :name, :email

  before_filter do
    @user = current_user || User.new(params[:user])
  end

  def new
    return redirect_to edit_user_url if logged_in?
  end

  def show
  end

  def edit
  end

  def create
    User.where(email: params.require(:user)[:email], email_active: false, role: nil).delete_all
    if @user.save
      redirect_to root_url, notice: "登録しました"
    else
      render "new"
    end
  end

  def omniauth
    omni_hash = request.env['omniauth.auth'] or return redirect_to root_path, notice: "認証に失敗しました"
    auth = Auth.find_or_create_by_provider_and_uid(omni_hash['provider'], omni_hash['uid'])
    auth.omni_hash = omni_hash
    unless auth.user
      auth.user = User.new(name: omni_hash.info['nickname'], role: :contributor)
      auth.user.save!(validate: false)
    end
    auth.save!

    auto_login(auth.user)
    redirect_to root_url, notice: "ログインしました"
  end

  def update(user)
    if @user.update_attributes(user)
      redirect_to user_url , notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy

    redirect_to root_url, notice: "User was successfully deleted."
  end

  def resend_activation
    if @user.email.present?
      UserMailer.activate(@user).deliver
      redirect_to root_url, notice: "確認メールを送信しました"
    else
      redirect_to root_url, notice: "メールアドレスが登録されていません"
    end
  end

  def activate(key)
    user = User.find_by_key!(key)
    user.update_column(:email_active, true)
    redirect_to root_url, notice: "メールアドレスを確認しました"
  end

  def unsubscribe(key)
    user = User.find_by_key!(key)
    if user.auths.count > 0
      user.update_column(:email, nil)
    else
      user.destroy
    end
    redirect_to root_url, notice: "登録解除しました"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tags_tag(tags)
    tags.map do |tag|
      link = @current_tags.include?(tag) ? "#" : programs_path(tag: (@current_tags + [tag]).join(','))
      link_to tag, link, class: "badge"
    end.join.html_safe
  end
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/imports/new.html.haml
%h1 インポート
%form{for: import_path}
%table.table.table-striped
  = render @programs

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "MagicTv"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Magic TV
          .container.nav-collapse
            %ul.nav
              %li= link_to "番組一覧", programs_path
              %li= link_to "番組情報の投稿", can?(:create,:programs) ? new_program_path : "javascript:alert('ログインが必要です')"
              %li= link_to "インポート", new_import_path if can? :access, :import
            %ul.nav.pull-right
              - if logged_in?
                %li.dropdown
                  %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                    %i.icon-user.icon-white
                    = current_user.name
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to 'マイページ', edit_user_path
                    %li= link_to 'ログアウト', session_destroy_path
              - else
                %li.dropdown
                  %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                    ログイン
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to 'Twitter', "/auth/twitter"
                    %li= link_to 'Facebook', "/auth/facebook"
                    %li= link_to 'mixi', "/auth/mixi"
                    %li= link_to 'OpenID', "/auth/open_id"
                    %li= link_to 'メール登録', new_user_path
              %li= link_to glyph(:question_sign), help_user_path

    .container-fluid

      .row-fluid
        .span12
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; kuboon 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/programs/_form.html.haml
= simple_form_for @program, :html => { :class => 'form-horizontal' } do |f|
  = f.input :url
  = f.input :name
  = f.input :tag_list, input_html: {class: :tag_it}
  = f.input :channel
  = f.input :description, input_html: {rows: 5}
  = f.input :start_at, as: :date_time_picker
  = f.input :end_at, as: :date_time_picker
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), programs_path, :class => 'btn'

app/views/programs/_program.html.haml
%tr
  %td
    - if params[:controller] == "imports"
      = link_to glyph(:ok), moderate_program_path(program, :ok), method: :put, remote: :true
      = link_to glyph(:remove), moderate_program_path(program, :ng), method: :put, remote: :true
    - elsif can? :edit, program
      = link_to glyph(:pencil), edit_program_path(program)
      = link_to glyph(:trash), program_path(program), method: :delete, remote: :true
  %td=l program.start_at, format: "%m/%d(%a) %H:%M"
  %td
    = link_to program.name, program.url, target: "_blank"
    = tags_tag program.base_tags.map(&:name) # tag_list is slow
  %td= program.channel
  %td= program.description

app/views/programs/edit.html.haml
- model_class = Program
.page-header
  %h1 番組の編集
= render :partial => "form"

app/views/programs/index.html.haml
- model_class = Program
.page-header
  %h1 番組一覧
  %p 今後放送予定のマジック関連番組をご紹介しています。掲載されていない番組情報をお持ちの方は、アカウント登録の上、「番組情報の投稿」からお寄せ頂ければ幸いです。
  %p
    - @current_tags.each do |tag|
      %span{class: :badge}
        = tag
        = link_to glyph(:remove), programs_path(tag: (@current_tags - [tag]).join(','))
%table.table.table-striped
  = render @programs

app/views/programs/new.html.haml
- model_class = Program
.page-header
  %h1 番組情報の投稿
= render :partial => "form"

app/views/programs/show.html.haml
- model_class = Program
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%dl
  %dt= model_class.human_attribute_name(:url) + ':'
  %dd=  @program.url

  %dt= model_class.human_attribute_name(:name) + ':'
  %dd=  @program.name

  %dt= model_class.human_attribute_name(:channel) + ':'
  %dd=  @program.description

  %dt= model_class.human_attribute_name(:description) + ':'
  %dd=  @program.description

  %dt= model_class.human_attribute_name(:start_at) + ':'
  %dd=  @program.start_at

  %dt= model_class.human_attribute_name(:end_at) + ':'
  %dd=  @program.end_at

  %dt= model_class.human_attribute_name(:status) + ':'
  %dd=  @program.status

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), programs_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_program_path(@program), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), program_path(@program), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/users/_form.html.haml
= simple_form_for @user, url: user_path, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :email, hint: "登録すると週に2回メールが届くようになります。 #{link_to glyph(:question_sign), help_user_path}"
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), :back, :class => 'btn'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/users/help.html.haml
.page-header
  %h1 使い方

%section
  %h2 これは何？
  %p マジックのテレビ番組情報を配信するサービスです。

%section
  %h2 どうやって使うの？
  %p
    %a{href: programs_path}番組一覧
    から、本日以降の番組情報をご覧頂けます。番組をタグで絞り込むことも出来ます。

%section
  %h2 メールで受け取りたい
  %p #{link_to "メールアドレスをご登録", new_user_path}頂くと、金曜夜、火曜朝の2回、配信いたします。
  %p 番組情報とともに、関連広告を配信させていただく場合がございます。
  %p メールの配信は、メール末尾のURLからいつでも解除可能です。
  %p お預かりしたメールアドレスをその他の用途に流用することはございません。

%section
  %h2 機能についての意見要望は
  %p
    %a{href:"https://www.facebook.com/pages/Magictv/129782290547256"}Facebook
    上で受け付けております。

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%dl
  %dt= model_class.human_attribute_name(:name) + ':'
  %dd= @user.name

  %dt= model_class.human_attribute_name(:email) + ':'
  %dd
    = @user.email
    = @user.email.empty? ? "未登録" : @user.email_active? ? "認証済み" : raw("認証待ち(#{link_to "再送", resend_activation_user_path})")

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), :back, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path, :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path, :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'